### PR TITLE
Add detection for pdftk library.

### PR DESCRIPTION
**Pull request by elmatou**
Detection is automatic and non intrusive.

PdftkForms::Wrapper.new #=> use PdftkForms::Wrapper.path
PdftkForms::Wrapper.path #=> use PdftkForms::Wrapper.locate_pdftk & fallback on 'pdftk' in $PATH
You can set a default path, used for all new instances.
PdftkForms::Wrapper.path='my/path' #=> set the default path
Now 
PdftkForms:Wrapper.new #=> will use 'my/path'
but you can always set a specific path on each instance.
PdftkForms::Wrapper.new(:path => 'my/instance/path') => will use 'my/instance/path'

In most of case direct call to `PdftkForms::Wrapper.new` is enough

The project is very young and I decide to change the arguments to PdftkForms:Wrapper.new(options = {})
why : because explicit arguments is always better for non trivial case.
and because PdftkForms::Wrapper.new(nil, bla => bla, bla => blo) is not aestetic !
Fill free to ask to come back.

### CODE REVIEW

**Comment by elmatou** [comment]
I forget to explain a trick in the tests suite.
in order to test the detection of the library.
On a system you know call `rake path=/my/known/path` it will test the detection against the argument you pass to rake.
calling `rake` will skip the test (no failure).

**Comment by tcocca** [comment]
The only problem with this is that if you pass :path in the options to the initialize method it doesn't actually set the class variable @@path, it only sets a instance variable of path.  So I think the initialize method should be:

``` ruby
def initialize(options = {})
  if pdftk_path = options.delete(:path)
    Wrapper.path = pdftk_path
  end
  @options = options
end
```

and then the #call_pdftk method should use the getting for the class variable

``` ruby
def call_pdftk(*args)
  #TODO: raise error here if Wrapper.path is nil
  %x{#{Wrapper.path} #{args.flatten.compact.join ' '}}
end
```

Make sense?  The point is to only set the path once, so when you create a new instance of Wrapper and give it a path it should set it on the class and use that then on everywhere.

Also, we should no longer need the @path attr_accessor on the Wrapper class.

~ Tom

**Comment by tcocca** [comment]
By the way, I wholly agree on the change for the arguments to new, thanks for that.  Also if you don't agree on the initialize w/ path setting the class var let me know.  Having re-read your messge at the top, i'm now a little undecided.

~ Tom

**Comment by elmatou** [comment]
Hum...
I wanted to allow users to have various path, for various instances.... but is it usefull ? I don't know...
Your solution is simplier (it is a quality to me), but it make possible to change the path as a side affect.

``` ruby
@first = PdftkForms::Wrapper.new(:path => 'my/first/path') #=> will use 'my/first/path'
@second = PdftkForms::Wrapper.new(:path => 'my/second/path') #=> will use 'my/second/path'
# Now we'll see the side effect
@first.path #=> 'my/second/path'
```

That is why I copy the path to the instance...
I think it is not a good behaviour for a general purpose library (even if it could be good in a specific context.)

**Comment by tcocca** [comment]
OK thats reasonable to me.  I'm not sure why people would be using 2 different paths in the same app but thats fine.

I'll take this pull in tonight after work.

Thanks again,
~ Tom

**Comment by elmatou** [comment]
Great,
Like you I'm dubious, for the several paths ability, but those kind of side effects is not acceptable to me.

**Pull request merged**
