### PR TITLE
Version check + Pdftk::Form abstraction layer

### PR DESCRIPTION
**Pull request by elmatou**
Hi Tom,
Here is my work, fully tested (with Ruby 1.8.7)
Please test it on your system (you seems to run ruby 1.9.2, it will be a good test).

If you want to amend things do not hesitate.

Cheers !

### CODE REVIEW

**Comment by tcocca** [comment]
Merged this stuff with the trunk on this branch:  https://github.com/tcocca/pdftk_forms/commits/form_abstraction

Going to do some more testing and see about merging this into the master soon.

I am still leery about setting the value and overriding the default value that came with the field.  I probably wont merge this in to master till we can get the whole default_value thing worked out, which I think you already opened a ticket on.

If you want to do some work on that please work off my branch so we can make this easier (sorry if this is a huge pain for you).  I already updated this commit to work off the master with the new Wrapper path setting that I merged in yesterday.

**Comment by elmatou** [comment]
He ! 
I did open a ticket for the default_value (I call it dirty_fields as Rails do it for ActiveRecord), I did implement this feature in one of my branches, maybe I can pull/merge/push with your form_abstraction branch, even if I think it could be a core feature (merging it directly to master.).
See : https://github.com/tcocca/pdftk_forms/issues/7 & https://github.com/elmatou/pdftk_forms/tree/dirty-fields

**Comment by tcocca** [comment]
I agree, with the core feature.  Let me look into this tongiht.  I like the changed? method.  I would also like the see the changes method (like dirty attributes) too which returns a hash, I know only 1 attribute can change but sometimes it nice to have.  Unless you think just the changed? is enough.

One thing I would probably do is use the #value getter instead of calling attributes['FieldValue'] in setting @value_was and in the changed? method, its just a little cleaner to look at.

**Comment by elmatou** [comment]
I agree on all points,
take a look, and tell me which changes do you want before the P/R

**Comment by tcocca** [comment]
I commented on that commit in the dirty_attributes branch.  The reason I wanted to pull it into the form_abstraction branch was mainly due to my comments about the read_only thing.  I'd like to handle that on the field class but I guess the Form setter may need to due something about that as well, give some feedback if the field is readonly?  Maybe that is where we should return false in the #set method if the field is read_only?

**Comment by tcocca** [comment]
I pull the dirty stuff in to form_abstraction branch here https://github.com/tcocca/pdftk_forms/commit/0683a8af8843da5d81cbc9e9494cc3c8b6c08b05

I also implemented the changes method as well as not letting the value be written if its read only.  Got rid of the setters on the other field data as this stuff should never change anyway.

In this commit:  https://github.com/tcocca/pdftk_forms/commit/eee7f5a0fc65b9ecf767209e8ba35020059f9cc0

I return false in the form abstraction when you try and set the value on a read_only? field.

I'll probably be merging this branch in to the master soon if you think this stuff looks cool.

~ Tom

**Pull request closed without merging**
